name: CI/CD Pipeline

on:
  push:
    branches:
      [main]
  pull_request:
    branches:
      [main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Validate with Checkstyle
      run: mvn checkstyle:check

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Add artifact to repository
      run: mvn --batch-mode deploy
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
