name: CI/CD Pipeline

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:        
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    - name: Validate with Checkstyle
      run: mvn checkstyle:check

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app-jar
        path: target/*.jar

    - name: Add artifact to repository
      run: |
        git add .
        git commit -m "Add built artifact"
        git push origin main
